# Generated by Django 2.2.2 on 2019-08-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcessBaggageEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField(blank=True)),
                ('destination_country', models.CharField(max_length=50)),
                ('destination_city', models.CharField(max_length=50)),
                ('origin_country', models.CharField(max_length=50)),
                ('origin_city', models.CharField(max_length=50)),
                ('baggage_detail', models.TextField()),
                ('enquired_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetRelocationEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField(blank=True)),
                ('destination_country', models.CharField(max_length=50)),
                ('destination_city', models.CharField(max_length=50)),
                ('origin_country', models.CharField(max_length=50)),
                ('origin_city', models.CharField(max_length=50)),
                ('pet_detail', models.TextField()),
                ('req_depature_date', models.DateField()),
                ('enquired_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepatirationsEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField(blank=True)),
                ('relationship', models.CharField(max_length=100)),
                ('deceased_name', models.CharField(max_length=100)),
                ('deceased_location', models.TextField()),
                ('deceased_repatriated_to', models.TextField()),
                ('repatriation_insurance', models.BooleanField(default=False)),
                ('enquired_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
